"""Update user column

Revision ID: 80e9555a7dc0
Revises: a4a6f5428ff2
Create Date: 2024-12-02 09:37:35.885654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e9555a7dc0'
down_revision: Union[str, None] = 'a4a6f5428ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ref_income', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ref_income')
    # ### end Alembic commands ###
