"""init moigration

Revision ID: a4a6f5428ff2
Revises: 
Create Date: 2024-11-26 06:10:17.460506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a6f5428ff2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('rpc_url', sa.String(), nullable=False),
    sa.Column('last_checked_block', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('standard', sa.String(), nullable=True),
    sa.Column('decimal', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=True),
    sa.Column('last_checked_block', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_name', sa.String(), nullable=True),
    sa.Column('tg_username', sa.String(), nullable=True),
    sa.Column('active_address_id', sa.Integer(), nullable=True),
    sa.Column('address_limit', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('first_token_id', sa.Integer(), nullable=False),
    sa.Column('second_token_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_token_id'], ['token.id'], ),
    sa.ForeignKeyConstraint(['second_token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stake_token_id', sa.Integer(), nullable=False),
    sa.Column('reward_token_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reward_token_id'], ['token.id'], ),
    sa.ForeignKeyConstraint(['stake_token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tokens')
    op.drop_table('stake')
    op.drop_table('pool')
    op.drop_table('user')
    op.drop_table('token')
    op.drop_table('network')
    op.drop_table('address')
    # ### end Alembic commands ###
