"""Add tokens_limit

Revision ID: e54f1ccbbc8b
Revises: f1c62e9cb47c
Create Date: 2024-12-18 15:46:42.617214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54f1ccbbc8b'
down_revision: Union[str, None] = 'f1c62e9cb47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tokens_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tokens_limit')
    # ### end Alembic commands ###
