"""tg_id not unique

Revision ID: f1c62e9cb47c
Revises: 80e9555a7dc0
Create Date: 2024-12-04 20:01:38.039267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c62e9cb47c'
down_revision: Union[str, None] = '80e9555a7dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_tg_id_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_tg_id_key', 'user', ['tg_id'])
    # ### end Alembic commands ###
